import Head from "next/head";
import Sidebar from "../components/sidebar";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-black min-h-screen">
        <Sidebar />
      </main>
    </div>
  );
}
